# _config.yml
title: Your Documentation
tagline: Your tagline here
description: Your site description

url: 'https://d0s3nt.github.io'
baseurl: ''

# Directory settings
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      toc: true
      permalink: /:title/
  - scope:
      path: "_posts/*/images"
    values:
      image: true

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true

# Image processing settings
img_cdn: ''
assets:
  self_host:
    enabled: true
